from django.urls import path
from .views import (
    home,
    login_page,
    logout_page,
    signup_page,
    upload_page,
    summary_page,
    download_summary_pdf,
    analyze_video_api,
    stream_lecture_video,
    history_page,
    quiz_page,
    quiz_answer_page,
    tf_quiz_page,
    feedback_page,
    test_api,
    manage_dashboard,
    manage_answers,
    manage_users,
    save_calendar_memo,
    set_preferred_language,
)

urlpatterns = [
    path('', home, name='home'),
    path('login/', login_page, name='login'),
    path('logout/', logout_page, name='logout'),
    path('signup/', signup_page, name='signup'),
    path('upload/', upload_page, name='upload'),
    path('summary/', summary_page, name='summary'),
    path('summary/<int:lecture_id>/pdf/', download_summary_pdf, name='download_summary_pdf'),
    path('lecture-video/<int:lecture_id>/stream/', stream_lecture_video, name='stream_lecture_video'),
    path('analyze-api/', analyze_video_api, name='analyze_api'),
    path('history/', history_page, name='history'),
    path('quiz/', quiz_page, name='quiz'),
    path('quiz/answer/', quiz_answer_page, name='quiz_answer'),
    path('tf-quiz/', tf_quiz_page, name='tf_quiz'),
    path('feedback/', feedback_page, name='feedback'),
    path('api/test/', test_api, name='test_api'),
    path('api/calendar-memo/', save_calendar_memo, name='save_calendar_memo'),
    path('i18n/setlang/', set_preferred_language, name='set_language'),
    path('manage/', manage_dashboard, name='manage_dashboard'),
    path('manage/answers/', manage_answers, name='manage_answers'),
    path('manage/users/', manage_users, name='manage_users'),
]