# Generated by Django 6.0.4 on 2026-04-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_quiz'),
    ]

    operations = [
        # 먼저 lecture 필드를 ForeignKey로 바꿔서 lecture_id unique 제약 문제를 제거한다.
        migrations.AlterField(
            model_name='quiz',
            name='lecture',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quizzes',
                to='lectures.lecture'
            ),
        ),

        migrations.AddField(
            model_name='quiz',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='generation_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]