# Generated by Django 6.0.4 on 2026-05-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_quizquestion_related_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='summary_timeline',
            field=models.TextField(blank=True, help_text="키워드별 타임라인, 줄마다 '키워드 (분:초)' 형식"),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='human_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='predicted_label',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
