# Generated by Django 6.1.1 on 2026-09-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0011_userprofile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('processing', '분석 중'), ('completed', '완료'), ('failed', '실패')], db_index=True, default='pending', max_length=20),
        ),
    ]
